---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tails-server.deploy-name" . }}-allow-ingress
  labels:
    {{- include "tails-server.labels" . | nindent 4 }}
    name: {{ include "tails-server.deploy-name" . }}-allow-ingress
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.ingress.namespace }}
  podSelector:
    matchLabels:
      {{- include "tails-server.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
