---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tails-server.deploy-name" . }}
  labels:
    {{- include "tails-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
