---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tails-server.service-name" . }}
  labels:
    {{- include "tails-server.labelsWithName" . | nindent 4 }}
spec:
  ports:
    - name: {{ .Values.deploy.name.prefix }}-http
      port: {{ int .Values.service.port }}
      protocol: TCP
      targetPort: {{ int .Values.service.port }}
  selector:
    {{- include "tails-server.selectorLabels" . | nindent 4 }}
