version: "3"
services:
  tails-server:
    image: 989259452539.dkr.ecr.us-west-2.amazonaws.com/wmg-indy-tails-server-yfnxbsp6m4qv:latest
    ports:
      - 6543:6543
    networks:
      - tails-server
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path /data
        --log-level debug
    volumes:
      - ./data:/data
networks:
  tails-server:
